import * as React from 'react';
import { cn } from '../lib/utils';
export function Surface({className,...props}:React.ComponentProps<'div'>){return <div data-polli="surface" className={cn('rounded-xl bg-muted p-6',className)} {...props}/>}
export function Separator({className,...props}:React.ComponentProps<'hr'>){return <hr data-polli="separator" className={cn('my-6 border-0 border-t border-border',className)} {...props}/>}
export function Skeleton({className,...props}:React.ComponentProps<'div'>){return <div data-polli="skeleton" aria-hidden="true" className={cn('h-4 animate-pulse rounded-full bg-muted',className)} {...props}/>}
export function Avatar({name,src,className,...props}:React.ComponentProps<'span'> & {name:string;src?:string}){return <span data-polli="avatar" role="img" aria-label={name} className={cn('inline-flex size-11 shrink-0 items-center justify-center overflow-hidden rounded-full bg-mint text-sm font-medium text-[#21352D]',className)} {...props}>{src?<img src={src} alt="" className="size-full object-cover"/>:name.split(' ').map(p=>p[0]).slice(0,2).join('')}</span>}
export function EmptyState({title,description,action,icon}: {title:string;description:string;action?:React.ReactNode;icon?:React.ReactNode}){return <div data-polli="empty-state" className="grid justify-items-center gap-3 py-12 text-center">{icon}<h3 className="m-0 text-lg font-semibold">{title}</h3><p className="m-0 max-w-sm text-sm text-muted-foreground">{description}</p>{action}</div>}
export function ListRow({leading,title,description,trailing,className,...props}:Omit<React.ComponentProps<'div'>,'title'> & {leading?:React.ReactNode;title:React.ReactNode;description?:React.ReactNode;trailing?:React.ReactNode}){return <div data-polli="list-row" className={cn('flex items-center gap-4 rounded-lg py-4',className)} {...props}>{leading}<div className="min-w-0 flex-1"><div className="text-sm font-medium">{title}</div>{description?<div className="mt-1 text-sm text-muted-foreground">{description}</div>:null}</div>{trailing}</div>}
export function Alert({title,children,className,...props}:Omit<React.ComponentProps<'div'>,'title'> & {title:string}){return <div data-polli="alert" role="status" className={cn('rounded-lg bg-mint p-4 text-[#21352D]',className)} {...props}><div className="text-sm font-medium">{title}</div><div className="mt-1 text-sm">{children}</div></div>}
